terrain = "volcanoterrain.cfg"
width = 750.0
height = 750.0
spawn_point = [
    97.7,
    10.0,
    632.9000000000001,
]
weather_cycle = "Redsky"

[[portals]]
pos = [
    108.80000000000001,
    632.3000000000001,
    88.0,
]
range = 2.5
destination = "Default"

[[portals]]
pos = [
    396.8,
    391.0,
    165.0,
]
range = 2.5
destination = "Jungle"

[[portals]]
pos = [
    507.5,
    332.5,
    110.0,
]
range = 2.5
destination = "Lava"

[[portals]]
pos = [
    336.5,
    371.8,
    1.5,
]
range = 2.5
destination = "Ocean"

[[water_planes]]
pos = [
    324.0,
    377.8,
    170.0,
]
scale_x = 60.0
scale_z = 60.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    605.0,
    172.5,
    60.0,
]
scale_x = 70.0
scale_z = 70.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    689.2,
    667.7,
    42.5,
]
scale_x = 275.0
scale_z = 375.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    212.5,
    648.5,
    29.5,
]
scale_x = 75.0
scale_z = 75.0
sound = "water1.wav"

[[water_planes]]
pos = [
    243.5,
    40.5,
    46.0,
]
scale_x = 100.0
scale_z = 100.0
sound = "water1.wav"

[[particles]]
name = "WaterfallSmoke"
pos = [
    214.8,
    661.1,
    29.0,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    206.0,
    649.8000000000001,
    29.0,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    216.0,
    640.0,
    29.0,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    270.3,
    38.5,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    243.10000000000002,
    47.1,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    228.3,
    39.1,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    220.70000000000002,
    39.6,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    257.40000000000003,
    49.800000000000004,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    254.9,
    37.0,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    215.9,
    45.0,
    45.5,
]

[[particles]]
name = "Geyser"
pos = [
    196.20000000000002,
    29.400000000000002,
    50.2,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    564.0,
    366.0,
    90.2,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    51.0,
    247.60000000000002,
    89.5,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    236.4,
    658.5,
    51.0,
]
sound = "Steam2.wav"
