width = 750.0
height = 750.0
spawn_point = [
    97.7,
    740.0,
    632.9000000000001,
]
weather_cycle = "Redsky"

[[portals]]
pos = [
    108.80000000000001,
    117.69999999999993,
    88.0,
]
range = 2.5
destination = "Default"

[[portals]]
pos = [
    396.8,
    359.0,
    165.0,
]
range = 2.5
destination = "Jungle"

[[portals]]
pos = [
    507.5,
    417.5,
    110.0,
]
range = 2.5
destination = "Lava"

[[portals]]
pos = [
    336.5,
    378.2,
    1.5,
]
range = 2.5
destination = "Ocean"

[[water_planes]]
pos = [
    324.0,
    372.2,
    170.0,
]
scale_x = 60.0
scale_z = 60.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    605.0,
    577.5,
    60.0,
]
scale_x = 70.0
scale_z = 70.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    689.2,
    82.29999999999995,
    42.5,
]
scale_x = 275.0
scale_z = 375.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    212.5,
    101.5,
    29.5,
]
scale_x = 75.0
scale_z = 75.0
sound = "water1.wav"

[[water_planes]]
pos = [
    243.5,
    709.5,
    46.0,
]
scale_x = 100.0
scale_z = 100.0
sound = "water1.wav"

[[particles]]
name = "WaterfallSmoke"
pos = [
    214.8,
    88.89999999999998,
    29.0,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    206.0,
    100.19999999999993,
    29.0,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    216.0,
    110.0,
    29.0,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    270.3,
    711.5,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    243.10000000000002,
    702.9,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    228.3,
    710.9,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    220.70000000000002,
    710.4,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    257.40000000000003,
    700.2,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    254.9,
    713.0,
    45.5,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    215.9,
    705.0,
    45.5,
]

[[particles]]
name = "Geyser"
pos = [
    196.20000000000002,
    720.6,
    50.2,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    564.0,
    384.0,
    90.2,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    51.0,
    502.4,
    89.5,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    236.4,
    91.5,
    51.0,
]
sound = "Steam2.wav"
