terrain = "iceterrain.cfg"
width = 800.0
height = 800.0
spawn_point = [
    400.0,
    790.0,
    400.0,
]
weather_cycle = "Snow"
map_effect = "Exhale"

[[portals]]
pos = [
    485.1,
    414.79999999999995,
    28.8,
]
range = 2.5
destination = "Default"

[[portals]]
pos = [
    753.7,
    284.9,
    26.0,
]
range = 2.5
destination = "Waterfall"

[[portals]]
pos = [
    312.40000000000003,
    343.4,
    30.0,
]
range = 2.5
destination = "Lava"

[[portals]]
pos = [
    665.7,
    397.5,
    30.0,
]
range = 2.5
destination = "Ocean"

[[portals]]
pos = [
    624.7,
    709.5,
    30.0,
]
range = 2.5
destination = "ReallyBig"

[[gates]]
material = "GateMatBlack"
pos = [
    559.0,
    587.0,
    28.400000000000002,
]
destination = "Ice Cave"
dest_pos = [
    62.2,
    82.80000000000001,
]

[[water_planes]]
pos = [
    400.0,
    400.0,
    25.0,
]
scale_x = 1500.0
scale_z = 1500.0
material = "Terrain/FrozenWater"
sound = "wind1.wav"
is_solid = true
