width = 200.0
height = 200.0
spawn_point = [
    100.0,
    190.0,
    100.0,
]

[[gates]]
material = "GateMatWhite"
pos = [
    50.0,
    189.5,
    57.6,
]
destination = "Underwater Cave"
dest_pos = [
    22.3,
    119.1,
    3.1,
]

[[gates]]
material = "GateMatWhite"
pos = [
    144.9,
    9.0,
    57.6,
]
destination = "Last Cave"
dest_pos = [
    486.70000000000005,
    185.8,
]

[[water_planes]]
pos = [
    100.0,
    100.0,
    57.0,
]
scale_x = 1000.0
scale_z = 1000.0
material = "Terrain/LargeWater"

[interior]
height = 92.0
material = "Terrain/UnderwaterCeiling"
sky_color = [
    0,
    0,
    0,
    0,
]

[[lights]]
pos = [
    52.5,
    187.0,
    57.6,
]
color = [
    0.75,
    0.74,
    0.72,
]

[[lights]]
pos = [
    143.20000000000002,
    11.0,
    57.6,
]
color = [
    0.75,
    0.74,
    0.72,
]

[[billboards]]
pos = [
    52.5,
    187.0,
    57.6,
]
scale = [
    6.0,
    6.0,
]
material = "CaveLight"

[[billboards]]
pos = [
    142.9,
    11.399999999999977,
    57.6,
]
scale = [
    10.0,
    10.0,
]
material = "CaveLight"

[[sphere_walls]]
pos = [
    100.0,
    100.0,
    0.0,
]
range = 99.0
is_inside = false
