width = 500.0
height = 500.0
spawn_point = [
    90.0,
    499.9,
    200.0,
]

[[portals]]
pos = [
    94.0,
    422.0,
    12.0,
]
range = 2.5
destination = "Default"

[[water_planes]]
pos = [
    110.0,
    410.0,
    28.0,
]
scale_x = 110.0
scale_z = 110.0
sound = "water1.wav"

[grass]
material = "grass"
map = "grassdensitymap2.png"
color_map = "grass_tex.jpg"

[random_trees]
trees = [
    "Fir14-25.gltf",
    "Fir06-30.gltf",
    "Fir05-30.gltf",
]
count = 350

[random_bushes]
bushes = [
    "Farn.gltf",
    "Plant2.gltf",
    "Shroom1-1.gltf",
]
