terrain = "lavaterrain.cfg"
width = 800.0
height = 800.0
spawn_point = [
    400.0,
    10.0,
    400.0,
]
weather_cycle = "Redsky"

[[portals]]
pos = [
    396.70000000000005,
    65.3,
    41.6,
]
range = 2.5
destination = "ReallyBig"

[[portals]]
pos = [
    134.3,
    304.3,
    55.1,
]
range = 2.5
destination = "Default"

[[portals]]
pos = [
    576.6,
    51.5,
    10.0,
]
range = 1.0
destination = "Waterfall"

[[portals]]
pos = [
    53.300000000000004,
    40.300000000000004,
    60.0,
]
range = 2.5
destination = "Ice"

[[portals]]
pos = [
    643.6,
    725.1,
    39.0,
]
range = 3.0
destination = "Jungle"

[[portals]]
pos = [
    343.20000000000005,
    478.20000000000005,
    37.0,
]
range = 2.0
destination = "Volcano"

[[gates]]
material = "GateMatBlack"
pos = [
    511.5,
    319.0,
    39.5,
]
destination = "Lava Cave"
dest_pos = [
    48.2,
    89.0,
]

[[water_planes]]
pos = [
    531.6,
    347.1,
    38.0,
]
scale_x = 100.0
scale_z = 100.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    15.700000000000001,
    82.0,
    55.1,
]
scale_x = 15.0
scale_z = 15.0
sound = "water1.wav"

[[water_planes]]
pos = [
    576.6,
    51.5,
    7.0,
]
scale_x = 20.0
scale_z = 20.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    352.1,
    649.8000000000001,
    40.0,
]
scale_x = 20.0
scale_z = 20.0
material = "Terrain/Magma"
sound = "lava1.wav"

[[water_planes]]
pos = [
    677.2,
    748.0,
    25.0,
]
scale_x = 40.0
scale_z = 50.0
sound = "water1.wav"

[[water_planes]]
pos = [
    390.70000000000005,
    687.5,
    38.0,
]
scale_x = 37.0
scale_z = 50.0
sound = "water1.wav"

[[water_planes]]
pos = [
    417.8,
    517.2,
    13.5,
]
scale_x = 5000.0
scale_z = 5000.0
material = "Terrain/LargeMagma"
sound = "lava1.wav"

[[particles]]
name = "WaterfallSmoke"
pos = [
    683.0,
    747.3000000000001,
    24.1,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    668.7,
    750.5,
    24.3,
]

[[particles]]
name = "WaterfallSmoke"
pos = [
    385.5,
    683.0,
    38.400000000000006,
]

[[particles]]
name = "Geyser"
pos = [
    390.5,
    269.1,
    50.0,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    385.6,
    261.3,
    50.1,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    390.8,
    277.5,
    47.5,
]
sound = "Steam1.wav"

[[particles]]
name = "Geyser"
pos = [
    611.3000000000001,
    431.90000000000003,
    45.0,
]
sound = "Steam1.wav"

[[particles]]
name = "Geyser"
pos = [
    444.70000000000005,
    352.5,
    58.400000000000006,
]
sound = "Steam2.wav"

[[particles]]
name = "Geyser"
pos = [
    492.8,
    469.6,
    25.6,
]
sound = "Steam2.wav"
