width = 5000.0
height = 5000.0
spawn_point = [
    2500.0,
    4990.0,
    2500.0,
]
weather_cycle = "ThunderstormRain"

[[portals]]
pos = [
    2560.0,
    2440.0,
    27.0,
]
range = 2.5
destination = "Default"

[[portals]]
pos = [
    3700.0,
    525.0,
    18.0,
]
range = 2.5
destination = "Waterfall"

[[portals]]
pos = [
    4900.0,
    4924.5,
    4.0,
]
range = 1.5
destination = "Forest"

[[portals]]
pos = [
    2480.0,
    2505.0,
    28.0,
]
range = 3.0
destination = "Ocean"

[grass]
material = "yellowGrass"
map = "grassdensitymap.png"
color_map = "grass_tex.jpg"

[random_trees]
trees = [
    "Fir14-25.gltf",
    "Fir06-30.gltf",
    "Fir05-30.gltf",
]
count = 500
