[[layers]]
texture = "grass_tex2.png"
scale = [
    0.01,
    0.01
]

[[layers]]
texture = "rock_tex1.png"
scale = [
    0.01,
    0.01
]

[[layers]]
texture = "sand_tex2.png"
scale = [
    0.01,
    0.01
]
