terrain = "lastCaveterrain.cfg"
width = 1000.0
height = 1000.0
spawn_point = [
    487.3,
    0.1,
    14.0,
]

[[gates]]
material = "GateMatWhite"
pos = [
    487.3,
    2.5,
    54.0,
]
destination = "Serpent's Pass"
dest_pos = [
    138.4,
    180.5,
    57.6,
]

[[water_planes]]
pos = [
    500.0,
    500.0,
    52.0,
]
scale_x = 1250.0
scale_z = 1250.0
material = "Terrain/LargeWater"

[interior]
height = 90.0
material = "Terrain/UnderwaterCeiling"
sky_color = [
    0,
    0,
    0,
    0,
]

[[lights]]
pos = [
    487.3,
    6.0,
    54.0,
]
color = [
    0.75,
    0.74,
    0.72,
]

[[billboards]]
pos = [
    487.3,
    6.0,
    54.0,
]
scale = [
    10.0,
    10.0,
]
material = "CaveLight"
