width = 100.0
height = 100.0
spawn_point = [
    50.0,
    90.0,
    50.0,
]

[[gates]]
material = "GateMatWhite"
pos = [
    47.0,
    5.599999999999994,
    13.0,
]
destination = "Waterfall"
dest_pos = [
    159.0,
    119.9,
]

[[water_planes]]
pos = [
    50.0,
    50.0,
    12.0,
]
scale_x = 100.0
scale_z = 100.0
sound = "water1.wav"

[interior]
height = 20.0
material = "WaterfallCaveCeiling"
sky_color = [
    0,
    0,
    0,
    0,
]

[[lights]]
pos = [
    47.0,
    5.599999999999994,
    13.0,
]
color = [
    0.75,
    0.74,
    0.72,
]

[[lights]]
pos = [
    50.0,
    49.5,
    13.200000000000001,
]
color = [
    0.1,
    0.9,
    1.0,
]

[[lights]]
pos = [
    49.5,
    50.5,
    13.200000000000001,
]
color = [
    0.1,
    0.9,
    1.0,
]

[[billboards]]
pos = [
    47.2,
    10.5,
    13.0,
]
scale = [
    6.0,
    6.0,
]
material = "CaveLight"

[[sphere_walls]]
pos = [
    50.0,
    50.0,
    0.0,
]
range = 40.0
is_inside = false

[[objects]]
mesh = "Crystal.gltf"

[[objects.instances]]
pos = [
    50.0,
    50.0,
]
rot = [
    0.0,
]
scale = [
    0.25,
]

[[objects.instances]]
pos = [
    51.0,
    49.6,
]
rot = [
    180.0,
]
scale = [
    0.17,
]

[[objects.instances]]
pos = [
    49.0,
    51.5,
]
rot = [
    155.0,
]
scale = [
    0.1,
]

[[objects.instances]]
pos = [
    48.800000000000004,
    49.2,
]
rot = [
    90.0,
]
scale = [
    0.13999999999999999,
]
