terrain = "oceanterrain.cfg"
width = 800.0
height = 800.0
spawn_point = [
    400.0,
    2.5,
    390.0,
]

[[portals]]
pos = [
    125.0,
    100.0,
    30.0,
]
range = 2.5
destination = "Default"

[[portals]]
pos = [
    90.0,
    710.0,
    12.0,
]
range = 5.0
destination = "Waterfall"

[[gates]]
material = "GateMatBlack"
pos = [
    429.20000000000005,
    416.1,
    14.0,
]
destination = "Underwater Cave"
dest_pos = [
    21.700000000000003,
    67.60000000000001,
    485.90000000000003,
]

[[water_planes]]
pos = [
    400.0,
    400.0,
    60.0,
]
scale_x = 1500.0
scale_z = 1500.0
material = "Terrain/LargeWater"
sound = "water1.wav"

[grass]
material = "yellowGrass"
map = "grassdensitymap.png"
color_map = "grass_tex.jpg"
